# This file was generated by GoReleaser. DO NOT EDIT.
cask "axiom" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "e887a8e1c8a721f7f739e82ed2312d2cf9c1212e5b3efe7ad277b69f9a9d8b16"
      url "https://github.com/axiomhq/cli/releases/download/v#{version}/axiom_#{version}_darwin_amd64_homebrew.tar.gz"
    end
    on_arm do
      sha256 "e5b1d605638a45b7f11eed96d44eac48a6f4806afb1e74981432d57df191a3f4"
      url "https://github.com/axiomhq/cli/releases/download/v#{version}/axiom_#{version}_darwin_arm64_homebrew.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a03c94956a20784c8a898e6a577b9d6235ddea3a795d1cad4227c135339f055"
      url "https://github.com/axiomhq/cli/releases/download/v#{version}/axiom_#{version}_linux_amd64_homebrew.tar.gz"
    end
    on_arm do
      sha256 "069d8c43efb98954f6cb0a6a740dd86789e5db4dc209af592725391b81be767c"
      url "https://github.com/axiomhq/cli/releases/download/v#{version}/axiom_#{version}_linux_arm64_homebrew.tar.gz"
    end
  end

  name "axiom"
  desc "Powerful log analytics from the comfort of your command-line"
  homepage "https://axiom.co"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axiom"
  manpage "man/axiom-annotation-create.1"
  manpage "man/axiom-annotation-delete.1"
  manpage "man/axiom-annotation-list.1"
  manpage "man/axiom-annotation-update.1"
  manpage "man/axiom-annotation.1"
  manpage "man/axiom-auth-login.1"
  manpage "man/axiom-auth-logout.1"
  manpage "man/axiom-auth-select.1"
  manpage "man/axiom-auth-status.1"
  manpage "man/axiom-auth-switch-org.1"
  manpage "man/axiom-auth-update-token.1"
  manpage "man/axiom-auth.1"
  manpage "man/axiom-completion-bash.1"
  manpage "man/axiom-completion-fish.1"
  manpage "man/axiom-completion-powershell.1"
  manpage "man/axiom-completion-zsh.1"
  manpage "man/axiom-completion.1"
  manpage "man/axiom-config-edit.1"
  manpage "man/axiom-config-export.1"
  manpage "man/axiom-config-get.1"
  manpage "man/axiom-config-set.1"
  manpage "man/axiom-config.1"
  manpage "man/axiom-dataset-create.1"
  manpage "man/axiom-dataset-delete.1"
  manpage "man/axiom-dataset-list.1"
  manpage "man/axiom-dataset-trim.1"
  manpage "man/axiom-dataset-update.1"
  manpage "man/axiom-dataset.1"
  manpage "man/axiom-ingest.1"
  manpage "man/axiom-query.1"
  manpage "man/axiom-stream.1"
  manpage "man/axiom-version.1"
  manpage "man/axiom-web.1"
  manpage "man/axiom.1"
  bash_completion "completions/axiom.bash"
  fish_completion "completions/axiom.fish"
  zsh_completion "completions/_axiom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axiom"]
    end
  end

  # No zap stanza required

end
