# This file was generated by GoReleaser. DO NOT EDIT.
cask "axiom" do
  desc "Powerful log analytics from the comfort of your command-line"
  homepage "https://axiom.co"
  version "0.14.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axiom"
  manpage "man/axiom.1"
  manpage "man/axiom-annotation.1"
  manpage "man/axiom-annotation-create.1"
  manpage "man/axiom-annotation-delete.1"
  manpage "man/axiom-annotation-list.1"
  manpage "man/axiom-annotation-update.1"
  manpage "man/axiom-auth.1"
  manpage "man/axiom-auth-login.1"
  manpage "man/axiom-auth-logout.1"
  manpage "man/axiom-auth-select.1"
  manpage "man/axiom-auth-status.1"
  manpage "man/axiom-auth-switch-org.1"
  manpage "man/axiom-auth-update-token.1"
  manpage "man/axiom-completion.1"
  manpage "man/axiom-completion-bash.1"
  manpage "man/axiom-completion-fish.1"
  manpage "man/axiom-completion-powershell.1"
  manpage "man/axiom-completion-zsh.1"
  manpage "man/axiom-config.1"
  manpage "man/axiom-config-edit.1"
  manpage "man/axiom-config-export.1"
  manpage "man/axiom-config-get.1"
  manpage "man/axiom-config-set.1"
  manpage "man/axiom-dataset.1"
  manpage "man/axiom-dataset-create.1"
  manpage "man/axiom-dataset-delete.1"
  manpage "man/axiom-dataset-list.1"
  manpage "man/axiom-dataset-trim.1"
  manpage "man/axiom-dataset-update.1"
  manpage "man/axiom-ingest.1"
  manpage "man/axiom-query.1"
  manpage "man/axiom-stream.1"
  manpage "man/axiom-version.1"
  manpage "man/axiom-web.1"
  bash_completion "completions/axiom.bash"
  zsh_completion "completions/_axiom"
  fish_completion "completions/axiom.fish"

  on_macos do
    on_intel do
      url "https://github.com/axiomhq/cli/releases/download/v0.14.7/axiom_0.14.7_darwin_amd64_homebrew.tar.gz"
      sha256 "31dcf90888d13413291970b4b453d63ed9b0aff0fe655ef027620ae3a0ccc079"
    end
    on_arm do
      url "https://github.com/axiomhq/cli/releases/download/v0.14.7/axiom_0.14.7_darwin_arm64_homebrew.tar.gz"
      sha256 "68206ea9cde042706fafd9d99f6907732a92d615b78abae96af6acd8e9766190"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axiom"]
    end
  end

  # No zap stanza required
end
