# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomLokiProxy < Formula
  desc "Loki powered log ingestion by proxy for Axiom"
  homepage "https://axiom.co"
  version "0.4.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.4.0/axiom-loki-proxy_0.4.0_darwin_amd64.tar.gz"
      sha256 "d291ef0a5c7d19a93d20db4557649caa0d1fff90c7630e7f3d84bd07a641f087"
    end
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.4.0/axiom-loki-proxy_0.4.0_darwin_arm64.tar.gz"
      sha256 "11308dd845549a5adbb864f8839005346739417afd4c915bd5e887c5da6ed2c4"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.4.0/axiom-loki-proxy_0.4.0_linux_armv6.tar.gz"
      sha256 "29c93c4369e84b6edd0ac18556caaa986174b5f62c07383bbba76f21e0de024e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.4.0/axiom-loki-proxy_0.4.0_linux_arm64.tar.gz"
      sha256 "5ad0cef8ff56e4ce6644c83e6fb666d57fa8f265088f218103eb7e7c9b325717"
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.4.0/axiom-loki-proxy_0.4.0_linux_amd64.tar.gz"
      sha256 "1fc8aad6e565ec53cc2dabe3299a0b2e9005e42b043ad1a7f70d0ad39a98eea7"
    end
  end

  def install
    bin.install "axiom-loki-proxy"
  end

  test do
    assert_match "x", "x"
  end
end
