# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomLokiMultiplexer < Formula
  desc "Loki powered log ingestion by multiplexer for Axiom"
  homepage "https://axiom.co"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.1/axiom-loki-multiplexer_0.6.1_darwin_amd64.tar.gz"
      sha256 "780e64810ad49ec9668c1c47b4b5c2fa98676adec888812c02cb15c0938128e9"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.1/axiom-loki-multiplexer_0.6.1_darwin_arm64.tar.gz"
      sha256 "b286a4f1fb7aa3cbf69d6a92ec784b566d5673c292b6b26681088bbed1bfb905"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.1/axiom-loki-multiplexer_0.6.1_linux_arm64.tar.gz"
      sha256 "911d03022c93571311bb6ee93bc13ddf06e4abffa58ba678565577ea3a333827"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.1/axiom-loki-multiplexer_0.6.1_linux_amd64.tar.gz"
      sha256 "b7e58df38e93ed75b49cdc63937673763dacffb4d83638ccddd08d155421291f"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.1/axiom-loki-multiplexer_0.6.1_linux_armv6.tar.gz"
      sha256 "ff7136dae40af7bf05c36253f9b390bab6889f48aa2de45d39ebad8ac7ec4e1e"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
