# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axiom < Formula
  desc "Powerful log analytics from the comfort of your command-line"
  homepage "https://axiom.co"
  version "0.2.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/axiomhq/cli/releases/download/v0.2.2/axiom_0.2.2_darwin_amd64.tar.gz"
    sha256 "c1e8f3071882e7904f6222f3fb9a269e93175b84ebdede709835d3000567e5e2"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/axiomhq/cli/releases/download/v0.2.2/axiom_0.2.2_darwin_arm64.tar.gz"
    sha256 "349815ac5afb416220d6c91c2f70a887df2950f047c5585f3694a18c38f1eb60"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/axiomhq/cli/releases/download/v0.2.2/axiom_0.2.2_linux_amd64.tar.gz"
    sha256 "6a1723357b05c7814c48a9e1ef059cfe51767a75bd0dc8b60ecf4755f35cd384"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/axiomhq/cli/releases/download/v0.2.2/axiom_0.2.2_linux_armv6.tar.gz"
    sha256 "4a794b3dc2eaeb916b6c58571163578d627fec435a9353bdb7baffc9d4d76f3f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/axiomhq/cli/releases/download/v0.2.2/axiom_0.2.2_linux_arm64.tar.gz"
    sha256 "75115002fc09480dd054fb807dec16fd529af106e08f667286aeb7cc25ec0412"
  end

  def install
    bin.install "axiom"
    man1.install Dir["man/axiom*.1"]
    (bash_completion/"axiom").write `#{bin}/axiom completion bash`
    (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
    (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
  end

  test do
    assert_match "Axiom CLI version #{version}", shell_output("#{bin}/axiom -v")
  end
end
