# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axiom < Formula
  desc "Powerful log analytics from the comfort of your command-line"
  homepage "https://axiom.co"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/cli/releases/download/v0.5.1/axiom_0.5.1_darwin_arm64.tar.gz"
      sha256 "00228727a04e08f83b4d34513f5c92d9306f3a1bbf62d022b39c5fb3bd81519c"

      def install
        bin.install "axiom"
        man1.install Dir["man/axiom*.1"]
        (bash_completion/"axiom").write `#{bin}/axiom completion bash`
        (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
        (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/cli/releases/download/v0.5.1/axiom_0.5.1_darwin_amd64.tar.gz"
      sha256 "90687c76493eae65a2d52d55bf3a6de3cbb4638e8b80778b71c2c221e103b5d0"

      def install
        bin.install "axiom"
        man1.install Dir["man/axiom*.1"]
        (bash_completion/"axiom").write `#{bin}/axiom completion bash`
        (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
        (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/cli/releases/download/v0.5.1/axiom_0.5.1_linux_arm64.tar.gz"
      sha256 "42bcfe5bc749356cad59eb9bfe55d6f1def1386e0ca09c7b20f121035182c93b"

      def install
        bin.install "axiom"
        man1.install Dir["man/axiom*.1"]
        (bash_completion/"axiom").write `#{bin}/axiom completion bash`
        (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
        (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/cli/releases/download/v0.5.1/axiom_0.5.1_linux_amd64.tar.gz"
      sha256 "ec32f51b13e42fffa08ead12bc198d7a305e937bf51b2f410f4e1d1693da4258"

      def install
        bin.install "axiom"
        man1.install Dir["man/axiom*.1"]
        (bash_completion/"axiom").write `#{bin}/axiom completion bash`
        (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
        (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/cli/releases/download/v0.5.1/axiom_0.5.1_linux_armv6.tar.gz"
      sha256 "10dd02357c44ea2d0555a599958113b0d4a9a934e4e94fc08c090c56c70afd3e"

      def install
        bin.install "axiom"
        man1.install Dir["man/axiom*.1"]
        (bash_completion/"axiom").write `#{bin}/axiom completion bash`
        (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
        (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
      end
    end
  end

  test do
    assert_match "Axiom CLI version #{version}", shell_output("#{bin}/axiom -v")
  end
end
