# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomSyslogProxy < Formula
  desc "Syslog ingestion by proxy for Axiom"
  homepage "https://axiom.co"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.6.1/axiom-syslog-proxy_0.6.1_darwin_arm64.tar.gz"
      sha256 "91dc4783bde709b01a3a181e88e5e1b3abf177274c38aee909800fe1354cb099"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.6.1/axiom-syslog-proxy_0.6.1_darwin_amd64.tar.gz"
      sha256 "402fb84544d5d82cae749b9d2cfb1979bf0ef0d17db365828fb611bd3dd9f241"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.6.1/axiom-syslog-proxy_0.6.1_linux_arm64.tar.gz"
      sha256 "2b92e3d873c55c4ae87cd9bf3d65c5e62b02d475f488f79e1ad6a39f029e71d0"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.6.1/axiom-syslog-proxy_0.6.1_linux_amd64.tar.gz"
      sha256 "fef1a808df2724571402b55c77cebcd7eff8ff19394ff8eace3d5624d4378728"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.6.1/axiom-syslog-proxy_0.6.1_linux_armv6.tar.gz"
      sha256 "3ece0d27a758cb18c09c82424a51273bb2753704873ae7d06b440dd242f2a47d"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
