# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomHostmetrics < Formula
  desc "Terminal UI that ships host metrics to Axiom via OTLP"
  homepage "https://axiom.co"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-hostmetrics/releases/download/v0.1.0/axiom-hostmetrics_0.1.0_darwin_amd64.tar.gz"
      sha256 "49d74ed77b874274c92160da18c6348a236a9a0fc17007ecce06efc55565591b"

      define_method(:install) do
        bin.install "axiom-hostmetrics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-hostmetrics/releases/download/v0.1.0/axiom-hostmetrics_0.1.0_darwin_arm64.tar.gz"
      sha256 "b7abee6522480d790271a1bcb6cdbab978aa551baac6e3e293ce0794fa815efc"

      define_method(:install) do
        bin.install "axiom-hostmetrics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-hostmetrics/releases/download/v0.1.0/axiom-hostmetrics_0.1.0_linux_amd64.tar.gz"
      sha256 "47553a6d5823a3e21b66acb755ddf0740bf0eb63266d6498f3a03ff950632e91"
      define_method(:install) do
        bin.install "axiom-hostmetrics"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-hostmetrics/releases/download/v0.1.0/axiom-hostmetrics_0.1.0_linux_armv6.tar.gz"
      sha256 "f4962fddeaf9899109ae2895e2c9459e4d663f6199a4c860f598a3633357317f"
      define_method(:install) do
        bin.install "axiom-hostmetrics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-hostmetrics/releases/download/v0.1.0/axiom-hostmetrics_0.1.0_linux_arm64.tar.gz"
      sha256 "d8466e155483cb61bd9791749aa2bbacf0f6c55611fc12b5d31489f1cb204b7b"
      define_method(:install) do
        bin.install "axiom-hostmetrics"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
