# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axiom < Formula
  desc "Powerful log analytics from the comfort of your command-line"
  homepage "https://axiom.co"
  version "0.1.9"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/axiomhq/cli/releases/download/v0.1.9/axiom_0.1.9_darwin_amd64.tar.gz"
    sha256 "9d013d2868a52563aeb6c6e995aa0158d8cf584903d50a0c6383767da7bfe277"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/axiomhq/cli/releases/download/v0.1.9/axiom_0.1.9_linux_amd64.tar.gz"
    sha256 "d2e2e410792b26c9164cddacb1ef82b21b47e6379254f97aa0081b7500d02386"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/axiomhq/cli/releases/download/v0.1.9/axiom_0.1.9_linux_arm64.tar.gz"
    sha256 "16e9c4576284efdb11a7876a817090a90800f0b8e1accd8e9c71f7a340c038b1"
  end

  def install
    bin.install "axiom"
    man1.install Dir["man/axiom*.1"]
    (bash_completion/"axiom").write `#{bin}/axiom completion bash`
    (fish_completion/"axiom.fish").write `#{bin}/axiom completion fish`
    (zsh_completion/"_axiom").write `#{bin}/axiom completion zsh`
  end

  test do
    assert_match "Axiom CLI version #{version}", shell_output("#{bin}/axiom -v")
  end
end
