# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomSyslogProxy < Formula
  desc "Syslog ingestion by proxy for Axiom"
  homepage "https://axiom.co"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.4.1/axiom-syslog-proxy_0.4.1_darwin_arm64.tar.gz"
      sha256 "337cc65f74a7295dfd5dd6e395d25d5251ef36091ea72f81b21fc5de6dca5165"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.4.1/axiom-syslog-proxy_0.4.1_darwin_amd64.tar.gz"
      sha256 "f2d248bdf6c4a2e9b25a0bc8954d270b4eef09983985b8b377004e9bea90f721"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.4.1/axiom-syslog-proxy_0.4.1_linux_armv6.tar.gz"
      sha256 "63f418a29fd2f35c9ab62eb7c844b96f458d4b26edb6a044a712e848c0136d42"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.4.1/axiom-syslog-proxy_0.4.1_linux_arm64.tar.gz"
      sha256 "b63759620f346adf06de754f82d262a2a99823812c092c2139a672450f988a06"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.4.1/axiom-syslog-proxy_0.4.1_linux_amd64.tar.gz"
      sha256 "6a99a1ee49daa472738b970792f2fba282c224773f7c967639c813d2bbef6acb"

      def install
        bin.install "axiom-syslog-proxy"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
