# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomLokiMultiplexer < Formula
  desc "Loki powered log ingestion by multiplexer for Axiom"
  homepage "https://axiom.co"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.0/axiom-loki-multiplexer_0.6.0_darwin_arm64.tar.gz"
      sha256 "f48e5778175aaeaaa935986830e9af4a4e1a23a6ce7b064eaed9cdb9af988e69"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.0/axiom-loki-multiplexer_0.6.0_darwin_amd64.tar.gz"
      sha256 "2d3f78bdf3a2a2199b95fa1bad6e202ccec97012986b22deaebcabc76750dc6f"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.0/axiom-loki-multiplexer_0.6.0_linux_arm64.tar.gz"
      sha256 "b3872682030ccbbc0716ae2c08550634556f38897f902efcab511415f6ba3505"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.0/axiom-loki-multiplexer_0.6.0_linux_amd64.tar.gz"
      sha256 "5ec219893627dc87a69277b378f660f9e72b675e5ce486936d2c245fbdd5cef9"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.6.0/axiom-loki-multiplexer_0.6.0_linux_armv6.tar.gz"
      sha256 "5ecfec1e47164f68c1fc305bf29b274e7c0695091ae8eed4d752bc8138833b3f"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
