# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomLokiProxy < Formula
  desc "Loki powered log ingestion by proxy for Axiom"
  homepage "https://axiom.co"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.2.0/axiom-loki-proxy_0.2.0_darwin_amd64.tar.gz"
      sha256 "adbb941f50a08e76c5c3d9fcf3aafffa69a7dd2566ab6a29046826dd4239e8ce"
    end
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.2.0/axiom-loki-proxy_0.2.0_darwin_arm64.tar.gz"
      sha256 "2e28b1dbdbddc43f17607b68a57fbb261322033e7b81b75d61aa665bfca5f079"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.2.0/axiom-loki-proxy_0.2.0_linux_amd64.tar.gz"
      sha256 "9095231cb0ec3d84e9dc9acb00eb20b2e5aea3390b22fc39dacf0c2952b76c9c"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.2.0/axiom-loki-proxy_0.2.0_linux_armv6.tar.gz"
      sha256 "8702e9b2bd3576b283713c57ee3893939136562b394c94b80ddd79fe3a1d7225"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-proxy/releases/download/v0.2.0/axiom-loki-proxy_0.2.0_linux_arm64.tar.gz"
      sha256 "288e37a5ed716ec8fe65959fa3ec27976a52d403089f3e8bdcdead92c18afe4a"
    end
  end

  def install
    bin.install "axiom-loki-proxy"
  end

  test do
    assert_match "x", "x"
  end
end
