# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomLokiMultiplexer < Formula
  desc "Loki powered log ingestion by multiplexer for Axiom"
  homepage "https://axiom.co"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.4.2/axiom-loki-multiplexer_0.4.2_darwin_arm64.tar.gz"
      sha256 "669be0041541f51b845998f3d41ad997a12eefe84820a86a4d63350406ac59be"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.4.2/axiom-loki-multiplexer_0.4.2_darwin_amd64.tar.gz"
      sha256 "8d7ea0ee191c415743641855ad25fea50c48bf5e7849d598172dca29d2596550"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.4.2/axiom-loki-multiplexer_0.4.2_linux_arm64.tar.gz"
      sha256 "483d53086ea21ad41fd7f79fe01187438536a982af84d4842bf97aca44659638"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.4.2/axiom-loki-multiplexer_0.4.2_linux_armv6.tar.gz"
      sha256 "a57c5e19922960ed6c2b16ad01d299e7396f14767e8d274b4ec64191fb7009d6"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-loki-multiplexer/releases/download/v0.4.2/axiom-loki-multiplexer_0.4.2_linux_amd64.tar.gz"
      sha256 "23d876ebb53d304c22be68773b2d06acc6903ad93d4c8c710eaf981b0fe385af"

      def install
        bin.install "axiom-loki-multiplexer"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
