# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxiomHoneycombProxy < Formula
  desc "Honeycomb compatible log forwarding and multiplexing proxy for Axiom"
  homepage "https://axiom.co"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-honeycomb-proxy/releases/download/v0.6.1/axiom-honeycomb-proxy_0.6.1_darwin_amd64.tar.gz"
      sha256 "30f6e56367539c82b97144161ac10dfea923f8adcb6b140acbe5d7d95997792b"

      def install
        bin.install "axiom-honeycomb-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axiomhq/axiom-honeycomb-proxy/releases/download/v0.6.1/axiom-honeycomb-proxy_0.6.1_darwin_arm64.tar.gz"
      sha256 "71b2639f79a0bdca0cd98ed9f0eef6f5ac998c2d76385b4d9b3573692a48758a"

      def install
        bin.install "axiom-honeycomb-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/axiomhq/axiom-honeycomb-proxy/releases/download/v0.6.1/axiom-honeycomb-proxy_0.6.1_linux_amd64.tar.gz"
      sha256 "4b3b636bdf0a4be09976155e471a01a8d1452b9d443b320a1f4455cc02d6a16e"

      def install
        bin.install "axiom-honeycomb-proxy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-honeycomb-proxy/releases/download/v0.6.1/axiom-honeycomb-proxy_0.6.1_linux_armv6.tar.gz"
      sha256 "6a23b732d8fb3e4b99247ca60c0bcb3c90305f74893268893fe7a68d101de827"

      def install
        bin.install "axiom-honeycomb-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axiomhq/axiom-honeycomb-proxy/releases/download/v0.6.1/axiom-honeycomb-proxy_0.6.1_linux_arm64.tar.gz"
      sha256 "ccea10251a350d08ce79f26922e786bb3f4b8e04c7f52e2079323030df08caa9"

      def install
        bin.install "axiom-honeycomb-proxy"
      end
    end
  end

  test do
    assert_match "x", "x"
  end
end
