name: brew

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        formula:
          - axiom
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Formula ${{ matrix.formula }}
        run: |
          brew audit ${{ matrix.formula }}
          brew install -v ${{ matrix.formula }}
          brew test ${{ matrix.formula }}
